version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: backend-core-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-backend_core}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped

  adminer:
    image: adminer:4.8.1
    container_name: backend-core-adminer
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    networks:
      - backend-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge